DEFAULT_ANDROID_SDK_ROOT = /Users/vantist/Library/Android/sdk
DEFAULT_ANDROID_NDK_ROOT = /Users/Vantist/Documents/Android_Resource/android-ndk-r10e
DEFAULT_ANDROID_PLATFORM = android-21
DEFAULT_ANDROID_NDK_HOST = darwin-x86_64
DEFAULT_ANDROID_TARGET_ARCH = arm64-v8a
DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION = 4.9
GCC_MACHINE_DUMP = 
